# -*- coding: utf-8 -*-
"""tts_llm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RV4yJIVGnd1Kd3BeuVrYpyPFXPjFIiTq
"""

# Install edge-tts and asyncio for TTS
!pip install edge-tts asyncio

import edge_tts
from IPython.display import Audio, display
import tempfile

async def play_tts(text, voice="en-US-JennyNeural"):

    # create temporary audio file
    with tempfile.NamedTemporaryFile(suffix=".mp3", delete=False) as f:
        filename = f.name

    # generate speech
    communicate = edge_tts.Communicate(text, voice=voice)
    await communicate.save(filename)

    # play audio directly in notebook
    display(Audio(filename, autoplay=True))

sample_text = """
Hello! Your stress level is currently high.
Please take a short break, breathe deeply, and focus on safe driving.
Your well-being is important for safe and responsible driving.
"""

await play_tts(sample_text)